name: narratur
favicon: null
layout_spectrum: 0.3749060982372612
typography_spectrum: 0.6740996937733144
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7058625109493732
  lightness: 0.30053755547851324
  saturation: 0.9114082111045718
  rhythmicContrast: 0.2325113129336387
purpose: []
